#!/bin/bash

## use fzf to search shell aliasees
## this crashes if nothing is sent into $1
function search_alias () {
    print -z $(alias | fzf --tac --select-1 --exit-0 --query "$1" | sed -nE 's/([a-zA-Z]*)=.*/\1/p')
}