#!/bin/bash

function toggle_vir_env () {
    if [ -v "$VIRTUAL_ENV" ]
    then
        deactivate
        echo "virtual env decactived"
    else
        python3 -m venv ./env; 
        source ./env/bin/activate
    fi
}