#!/bin/bash

###
# takes file location, opens in VScode and opens URL
# $1 local file location
# Optional
# $2 domain to open webpage ie https://localhost:3000/
# if #2 is empty, open at hc developer (localhost)
# -dev opens localhost:3000
# -prod asumes https://developer.hashicorp.com/
# if $2 is a number, it will be used to create the vercel URL

view_edit_tutorial() {
   if [ -z "${2:=http://localhost:3000/}" ]; then : 
   elif [ "$2" = "-dev" ]; then
      domain="http://localhost:3000/"
   # elif [  "$2" -eq "$2" ]; then
   elif [ "$2" = "-prod" ]; then
      domain="https://developer.hashicorp.com/"
   elif [[ "$2" =~ ^[0-9]+$ ]]; then
      domain="https://tutorials-git-${2}-hashicorp.vercel.app/"
   else domain="$2" 
   fi
   if [ ! -f "$1" ]; then 
      echo "Usage: view_edit_tutorial <file_path> [domain]"
   else
      collection=$(awk -F "[:/]" '$1=="default_collection_context" {print $3}' "$1") # searches the file
      file_name=$(echo "$1" | awk -F "[/.]" '{print $(NF-1)}') # this extracts from file name - should be grep
      # echo "${domain}/vault/tutorials/${collection}/${file_name}"
      open "${domain}/vault/tutorials/${collection}/${file_name}"
      sleep 1
      code "$1"
   fi
}